Repository Splendor-Mobile-Game/ServerSide, pull requests merged in 2023-03, with the labels that each got.

#6 Game model
  src/main/java/com/github/splendor_mobile_game/database/CardDatabase.java
  src/main/java/com/github/splendor_mobile_game/game/enums/CardTier.java
  src/main/java/com/github/splendor_mobile_game/game/enums/Color.java
  src/main/java/com/github/splendor_mobile_game/game/enums/TokenType.java
  src/main/java/com/github/splendor_mobile_game/game/model/Card.java
  src/main/java/com/github/splendor_mobile_game/game/model/Game.java
  src/main/java/com/github/splendor_mobile_game/game/model/Room.java
  src/main/java/com/github/splendor_mobile_game/game/model/Token.java
  src/main/java/com/github/splendor_mobile_game/game/model/TokenList.java
  src/main/java/com/github/splendor_mobile_game/game/model/User.java
  src/main/java/com/github/splendor_mobile_game/model/User.java
Labels: enhancement

#11 Refactor reactions for testability
  src/main/java/com/github/splendor_mobile_game/App.java
  src/main/java/com/github/splendor_mobile_game/websocket/communication/WebSocketSplendorServer.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/Message.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/Messenger.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/Reaction.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/CreateRoom.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/CreateServer.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/JoinRoom.java
Labels: refactor

#15 Move reaction's parameters to its constructor
  src/main/java/com/github/splendor_mobile_game/websocket/communication/WebSocketSplendorServer.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/Reaction.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/ReactionManager.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/CreateRoom.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/CreateServer.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/JoinRoom.java
  src/main/java/com/github/splendor_mobile_game/websocket/utils/reflection/Reflection.java
Labels: refactor

#32 Data field not required in requests if there is no dataclass
  src/main/java/com/github/splendor_mobile_game/websocket/communication/ReceivedMessage.java
  src/main/java/com/github/splendor_mobile_game/websocket/communication/WebSocketSplendorServer.java
  src/main/java/com/github/splendor_mobile_game/websocket/utils/json/Optional.java
Labels: enhancement

#36 Problem with model
  src/main/java/com/github/splendor_mobile_game/App.java
Labels: bug

#41 Move part of error handling to onError method
  src/main/java/com/github/splendor_mobile_game/websocket/communication/WebSocketSplendorServer.java
  src/main/java/com/github/splendor_mobile_game/websocket/utils/CustomException.java
  src/main/java/com/github/splendor_mobile_game/websocket/utils/reflection/CannotCreateInstanceException.java
Labels: refactor

#42 Added .idea folder to .gitignore
  .gitignore
Labels: refactor

#44 Make websockets more friendly to the client
  src/main/java/com/github/splendor_mobile_game/App.java
  src/main/java/com/github/splendor_mobile_game/database/InMemoryDatabase.java
  src/main/java/com/github/splendor_mobile_game/game/model/Game.java
  src/main/java/com/github/splendor_mobile_game/websocket/communication/ServerMessage.java
  src/main/java/com/github/splendor_mobile_game/websocket/communication/UserMessage.java
  src/main/java/com/github/splendor_mobile_game/websocket/communication/WebSocketSplendorServer.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/Messenger.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/Reaction.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/ReactionManager.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/ReactionType.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/ServerMessageType.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/UserRequestType.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/CreateRoom.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/CreateServer.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/DebugGetRandomCard.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/JoinRoom.java
  src/main/java/com/github/splendor_mobile_game/websocket/response/ErrorResponse.java
  src/main/java/com/github/splendor_mobile_game/websocket/utils/json/JsonParser.java
  src/test/java/com/github/splendor_mobile_game/websocket/handlers/reactions/CreateRoomTest.java
Labels: type: feature, type: refactor

#22 Add example of ResponseClass annotation
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/CreateRoom.java
Labels: type: feature

#50 Fix typo in EnvConfig constructor
  src/main/java/com/github/splendor_mobile_game/websocket/config/EnvConfig.java
Labels: type: fix

#40 Create LICENSE
  LICENSE
Labels: type: docs

#55 Create .github/workflows/maven.yml
  .github/workflows/maven.yml
Labels: effort: 3, type: security, type: testing, type: enhancement
