Repository Splendor-Mobile-Game/ServerSide, pull requests merged in 2023-04, with the labels that each got.

#60 Added LogLevel control
  src/main/java/com/github/splendor_mobile_game/websocket/utils/Log.java
Labels: type: enhancement

#45 Add java docs, also rename some classes and functions
  src/main/java/com/github/splendor_mobile_game/App.java
  src/main/java/com/github/splendor_mobile_game/websocket/communication/ConnectionCheckerWithoutDefaultConstructorException.java
  src/main/java/com/github/splendor_mobile_game/websocket/communication/ConnectionHandlerWithoutDefaultConstructorException.java
  src/main/java/com/github/splendor_mobile_game/websocket/communication/InvalidReceivedMessage.java
  src/main/java/com/github/splendor_mobile_game/websocket/communication/ServerMessage.java
  src/main/java/com/github/splendor_mobile_game/websocket/communication/UserMessage.java
  src/main/java/com/github/splendor_mobile_game/websocket/communication/WebSocketConnectionChecker.java
  src/main/java/com/github/splendor_mobile_game/websocket/communication/WebSocketConnectionHandler.java
  src/main/java/com/github/splendor_mobile_game/websocket/communication/WebSocketSplendorServer.java
  src/main/java/com/github/splendor_mobile_game/websocket/config/Config.java
  src/main/java/com/github/splendor_mobile_game/websocket/config/EnvConfig.java
  src/main/java/com/github/splendor_mobile_game/websocket/config/exceptions/EnvFileNotFoundException.java
  src/main/java/com/github/splendor_mobile_game/websocket/config/exceptions/EnvRequiredValueNotFoundException.java
  src/main/java/com/github/splendor_mobile_game/websocket/config/exceptions/EnvValueWrongTypeException.java
  src/main/java/com/github/splendor_mobile_game/websocket/config/exceptions/InvalidConfigException.java
  src/main/java/com/github/splendor_mobile_game/websocket/config/exceptions/UnsupportedEnvValueTypeException.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/DataClass.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/Message.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/Messenger.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/MissingFieldsException.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/Reaction.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/ReactionManager.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/ReactionName.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/ServerMessageType.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/UserRequestType.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/connection/ConnectionChecker.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/connection/ConnectionHandlerImpl.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/connection/SimpleConnectionChecker.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/CreateRoom.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/JoinRoom.java
  src/main/java/com/github/splendor_mobile_game/websocket/response/ErrorResponse.java
  src/main/java/com/github/splendor_mobile_game/websocket/response/Result.java
  src/main/java/com/github/splendor_mobile_game/websocket/utils/ColoredText.java
  src/main/java/com/github/splendor_mobile_game/websocket/utils/CustomException.java
  src/main/java/com/github/splendor_mobile_game/websocket/utils/Log.java
  src/main/java/com/github/splendor_mobile_game/websocket/utils/RandomString.java
  src/main/java/com/github/splendor_mobile_game/websocket/utils/json/JsonParser.java
  src/main/java/com/github/splendor_mobile_game/websocket/utils/json/Optional.java
  src/main/java/com/github/splendor_mobile_game/websocket/utils/json/exceptions/JsonIsNotValidJsonObject.java
  src/main/java/com/github/splendor_mobile_game/websocket/utils/json/exceptions/JsonIsNullException.java
  src/main/java/com/github/splendor_mobile_game/websocket/utils/json/exceptions/JsonMissingFieldException.java
  src/main/java/com/github/splendor_mobile_game/websocket/utils/json/exceptions/JsonParserException.java
  src/main/java/com/github/splendor_mobile_game/websocket/utils/reflection/CannotCreateInstanceException.java
  src/main/java/com/github/splendor_mobile_game/websocket/utils/reflection/Reflection.java
Labels: type: docs

#56 Added deletion of drawn card
  src/main/java/com/github/splendor_mobile_game/game/model/Deck.java
  src/main/java/com/github/splendor_mobile_game/game/model/Game.java
  src/main/java/com/github/splendor_mobile_game/game/model/TokenList.java
  src/test/java/com/github/splendor_mobile_game/game/model/GameTest.java
Labels: type: fix

#78 Check for missing request type and log error
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/ReactionManager.java
Labels: type: fix

#84 Refactor and document ServerMessage
  src/main/java/com/github/splendor_mobile_game/websocket/communication/ServerMessage.java
Labels: type: docs, type: refactor

#85 Refactor and document UserMessage
  src/main/java/com/github/splendor_mobile_game/websocket/communication/UserMessage.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/CreateRoom.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/DebugGetRandomCard.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/JoinRoom.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/LeaveRoom.java
Labels: type: docs, type: refactor

#87 Add getter for result in ServerMessage
  src/main/java/com/github/splendor_mobile_game/websocket/communication/ServerMessage.java
Labels: type: fix

#88 Functionality to check if user did some action in their turn
  src/main/java/com/github/splendor_mobile_game/game/model/User.java
Labels: type: feature

#92 Allow client to use rooms
  src/main/java/com/github/splendor_mobile_game/database/Database.java
  src/main/java/com/github/splendor_mobile_game/database/InMemoryDatabase.java
  src/main/java/com/github/splendor_mobile_game/database/SqliteDatabase.java
  src/main/java/com/github/splendor_mobile_game/game/model/User.java
  src/main/java/com/github/splendor_mobile_game/websocket/communication/ServerMessage.java
  src/main/java/com/github/splendor_mobile_game/websocket/communication/WebSocketConnectionChecker.java
  src/main/java/com/github/splendor_mobile_game/websocket/communication/WebSocketSplendorServer.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/connection/ConnectionChecker.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/connection/SimpleConnectionChecker.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/CreateRoom.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/JoinRoom.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/LeaveRoom.java
  src/main/java/com/github/splendor_mobile_game/websocket/response/ErrorResponse.java
  src/test/java/com/github/splendor_mobile_game/websocket/handlers/reactions/CreateRoomTest.java
Labels: type: fix

#97 Send stacktrace to client upon error
  src/main/java/com/github/splendor_mobile_game/websocket/communication/UserMessage.java
  src/main/java/com/github/splendor_mobile_game/websocket/communication/WebSocketSplendorServer.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/ServerMessageType.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/CreateRoom.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/JoinRoom.java
  src/main/java/com/github/splendor_mobile_game/websocket/handlers/reactions/LeaveRoom.java
  src/main/java/com/github/splendor_mobile_game/websocket/response/ErrorResponse.java
  src/main/java/com/github/splendor_mobile_game/websocket/utils/CustomException.java
  src/main/java/com/github/splendor_mobile_game/websocket/utils/ExceptionUtils.java
  src/main/java/com/github/splendor_mobile_game/websocket/utils/json/exceptions/JsonParserException.java
Labels: type: enhancement

#101 Improve find class with annotation
  src/main/java/com/github/splendor_mobile_game/websocket/communication/WebSocketSplendorServer.java
  src/main/java/com/github/splendor_mobile_game/websocket/utils/reflection/Reflection.java
Labels: type: refactor

#110 Better error messages when user forgot to provide some field
  src/main/java/com/github/splendor_mobile_game/websocket/communication/UserMessage.java
  src/main/java/com/github/splendor_mobile_game/websocket/communication/WebSocketSplendorServer.java
  src/main/java/com/github/splendor_mobile_game/websocket/utils/CustomException.java
  src/main/java/com/github/splendor_mobile_game/websocket/utils/json/JsonParser.java
Labels: type: enhancement

#112 Add reflection unit tests
  src/main/java/com/github/splendor_mobile_game/websocket/utils/reflection/Reflection.java
  src/test/java/com/github/splendor_mobile_game/websocket/utils/reflection/ReflectionTest.java
  src/test/java/com/github/splendor_mobile_game/websocket/utils/reflection/testClass.java
Labels: scope: 🧪

#120 Fix json parser
  src/main/java/com/github/splendor_mobile_game/websocket/utils/json/JsonParser.java
  src/test/java/com/github/splendor_mobile_game/websocket/utils/json/JsonParserTest.java
Labels: type: fix 🪠

#134 Use fields type to recursively check json
  src/main/java/com/github/splendor_mobile_game/websocket/utils/json/JsonParser.java
  src/test/java/com/github/splendor_mobile_game/websocket/handlers/reactions/CreateRoomTest.java
Labels: type: fix 🪠
